// A String is a subsequence of a given String, that is generated by deleting
//  some character of a given string without changing its order.

import java.util.ArrayList;

public class PrintAllSubsequence {
    static ArrayList<String> list = new ArrayList<>();
    public static void findSubSeq(String s, String ans){
        int n = s.length();
        if(n == 0){
            list.add(ans);
            return;
        }
        findSubSeq(s.substring(1, n), ans+s.charAt(0));
        findSubSeq(s.substring(1), ans);

    }
}
